version: "3"

services:
  postgres-db:
    container_name: "ritsoft-db"
    image: "postgres"
    environment:
      POSTGRES_USER: ritsoftadmin
      POSTGRES_PASSWORD: ritsoftadmin
      POSTGRES_DB: ritsoft
    ports:
      - "5421:5432"
    networks:
      - default

  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - default
    environment:
      # Db for laravel
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_DATABASE=ritsoft
      - DB_USERNAME=ritsoftadmin
      - DB_PASSWORD=ritsoftadmin

networks:
  default: