version: "3"

services:
    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: ritsoft
            POSTGRES_USER: ritsoft
            POSTGRES_PASSWORD: ritsoft
        networks:
            - app-network
        volumes:
            - "./db-data:/var/lib/postgresql"

    app:
        container_name: "ritsoft_app"
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - db
        networks:
            - app-network
        volumes:
            - "./src:/ritsoft"
            - "/ritsoft/node_modules"
            - "/ritsoft/vendor"
networks:
    app-network:
        driver: bridge
