on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and run the containers
        run: docker-compose up -d
      - name: Test
        run: curl localhost:3000
      - name: Lint
        uses: overtrue/phplint@master
