on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: sudo docker-compose up -d
      - name: Test
        run: sudo docker-compose run app php artisan test
      - name: Lint
        run: sudo docker-compose run app ./vendor/bin/phpcs --standard=PSR12 --extensions=php ./app ./routes
