on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: overtrue/phplint@3.0.2

  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run the containers
        run: docker-compose up -d
      - name: Curl
        run: chmod +x ./docker-test.sh && ./docker-test.sh