on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker-compose up -d
      - name: lint
        run: docker-compose run app ./vendor/bin/phpcs --standard=PSR12 --extensions=php ./app ./routes
